### ISSUE TITLE
Fazer a modelagem de agenda e dos eventos no banco

### ISSUE THREAD

**Issue by aguedamaiara** [PDSC-ReglusAcademy/BackEnd-Reglus#2]

**Comment by williemoliveiraa** [comment]
Link do modelo: [https://lucid.app/lucidchart/f6ea1f13-e623-480d-b97c-508d65836fcc/edit?viewport_loc=1211%2C-4301%2C4659%2C2155%2C0_0&invitationId=inv_6ffd3c17-9ec8-4d66-9f33-3287d5e8736b](url)
